### ISSUE TITLE
need help, where is the repositories dir

### ISSUE THREAD

**Issue by MOON-CLJ** [marvincaspar/go-web-app-boilerplate#14]
there are some comments in 

https://github.com/marvincaspar/go-web-app-boilerplate/blob/master/cmd/server/main.go#L23-L27

but where is the repositories?

**Comment by marvincaspar** [comment]
Currently these are placeholders where you can add your custom code. I (or someone else #hacktoberfest) can add some example code

**Comment by MOON-CLJ** [comment]
thx
